<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Inesh | Lead Generation</title>

<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">

<!-- mobile responsive meta -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!--Favicon-->
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">
  
  <style type="text/css">
    b{
      color: black;
    }
  </style>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<script>
$(function(){
$("#header1").load("header.php");
$("#footer1").load("footer.php");
$("#modal23").load("modal.php");
});
    </script>
</head>

<body>
<div class="page-wrapper">  
    

    <!-- Preloader -->
    <div class="preloader"></div>
    <!-- Preloader -->


   <div id="header1"></div>
    <!--End Main Header -->


    <!--Page Title-->
    <!-- <section class="page-title" style="background: url(images/background/2.jpg);">
        <div class="container text-center">
            <div class="title">
                <h4>Web Designing and Development</h4>
            </div>
            <ul class="title-manu">
                <li><a href="index.html">home</a></li>
                <li>></li>
                <li>Web Designing</li>
            </ul>         
        </div>
    </section> -->
    <!--End Page Title-->

    <!-- WEB DEVELOPMENT -->
        <div class="container" style="margin-top: 3rem;">
            <div class="section-title" style="margin-bottom: 4rem;">
                        <h2 class="text-center" style="font-size:3.2rem">Lead Generation</h2>
                    </div>
            <div class="row">
                <div class="col-sm-6">
                    
                    <p class="my-3 text-justify">
                      <!--  Leads for business act as a catalyst for the growth of the business and it can be considered as oxygen of business body which means it is highly essential for a business to grow in the market. Earlier leads were generated by door to door marketing, by cold calling and other tricks. However, at present things and world both have been changed now internet is the world and you need to be present on internet to boost your business, similarly internet and different tricks are used to generate leads. Online lead generation is the way to show your business, product or service to a bulk people by several means like email marketing, social media marketing, text messages, WhatsApp messages, YouTube marketing and lots of others.  -->
                  <?php 
                      include("connect.php");
                      $sql = 'SELECT * from `lead_main`';
                      $result = $conn->query($sql);

                      if ($result->num_rows > 0) {
                          // output data of each row
                          while($row = $result->fetch_assoc()) {
                              echo htmlspecialchars_decode($row['content']);
                          }
                      }
                      $conn->close();
                  ?>
                     </p>
                    <div class="row text-center" id="buttonn">
                        <button class="btn btn-lg btn-default" style="color: white; background-color:#E13737; border-radius: 0px!important; margin-top: 10vh; box-shadow: 1px 1px 1px 1px #E13737; border: 1px solid #E13737" data-toggle="modal" data-target="#myModal">
                            Request a quote&ensp;<span class="glyphicon glyphicon-arrow-right"></span>
                        </button>
                    </div>
                </div>
                <div class="col-sm-6">
                        <img class="img-fluid" style="height: 380px; width: 100%; " src="img/lead.png">
                    
                </div>
            </div>
    </div>

  <div id="modal23"></div>
    <br/><br/><br/>
<div class="container" >
    <div class="row">

        <div class="section-title" style="margin-bottom: 4rem;">
                    <h2 class="text-center">Overview</h2>
                </div>
                <p class="text-justify" style="margin-right: 5px; margin-left: 5px;">
<!--                   This era is data driven and you must be accurate while targeting your customers and at this point Inesh does the right thing for you, we gather data which is precisely belongs to your business and show your offers, products and services to them according to your niche so that maximum users may revert back or may show interest and which would act as a lead. So, the theory is so simple that offering your services or products to right users results into lead generation which we at Inesh understands and the value of your money. “Happy you Happy us”.Once a lead is generated you must be perfect to pitch your sales in best effective way with the best prices so that you may get the client. So only generation of lead does not mean you have got the business. 
 -->
                  <?php 
                      include("connect.php");
                      $sql = 'SELECT * from `lead_overview`';
                      $result = $conn->query($sql);

                      if ($result->num_rows > 0) {
                          // output data of each row
                          while($row = $result->fetch_assoc()) {
                              echo htmlspecialchars_decode($row['content']);
                          }
                      }
                      $conn->close();
                  ?>

</p>
    </div>
</div>



<br/><br/><br/>
            <div class="container" >
                <div class="row text-center" style="margin: 12px;">
                    <h3 class="text-center" style="font-size: 3rem; color: black!important">There are several online ways to generate or create a lead which are as follows:</h3>
<br/>

 <div class="row">
              <div class="col-lg-6 col-xs-12 dontknowthename " >
            <div class="cb-container"  >
                <div class="icon"><image src="img/hover/email marketing lead.png" width="60px" height="60px" style="margin-top:-35px"></div> 
                <br/> <br/>            
              <h4 class="title" Align="center" style="color:#0c2e8a"><a href="" style="color:#0c2e8a">Email Marketing</a></h4>
              <br/>
              <p class="description">Users land at your website by organic way or by any other method, he/she finds a form there which describes to fill user name, contact number and email ID once he does that you have his/her email ID and other details in your database which you can use to send or market your business, product or service with best possible offers.</p>
            </div>
          </div>
          
          <div class="col-lg-6 col-xs-12 dontknowthename">
              <div class="cb-container">
                <div class="icon"><image src="img/hover/social media marketing lead.png" width="60px" height="60px"  style="margin-top:-35px"></div>
                    <br/> <br/> 
                <h4 class="title" Align="center" style="color:#0c2e8a"><a href="" style="color:#0c2e8a">Social Media Marketing</a></h4>
                <br/>
                <p class="description"> Platforms like Facebook, LinkedIn, twitter, Instagram, Quora and lots of others where the whole world is spending most of the time from 24 hours. Few years ago, these platforms were used only for social connections but now they have also emerged as marketing platform for your business and by using the right strategies users are getting mind blowing results in the form of leads at these platforms.</p>
              </div>
            </div>  
          </div>
                </div>
            </div>

             <div class="container" >
                <div class="row text-center" style="margin: 12px;">
                    <h3 class="text-center" style="font-size: 3rem; color: black!important">There are other lead generation platforms which are providing good results if done in a right way: </h3>
<br/>
                   <div class="row">
          <div class="col-lg-3 col-xs-6 dontknowthename " >
            <div class="cb-container"  >
                <div class="icon"><image src="img/hover/bulkmsg.png" width="60px" height="60px" ></div> 
                <br/><br/> <br/>        
              <h4 class="description" Align="center" style="color:#0c2e8a"><a href="" style="color:#0c2e8a">Bulk messaging</a></h4>
            <br/> <br/> <br/>
            </div>
          </div>
          <div class="col-lg-3 col-xs-6 dontknowthename">
              <div class="cb-container">
                <div class="icon"><image src="img/hover/bulkmsgwtsp.png" width="60px" height="60px"  ></div>
                    <br/> <br/> <br/>
                <h4 class="description" Align="center" style="color:#0c2e8a"><a href="" style="color:#0c2e8a">Bulk messaging at WhatsApp</a></h4>
                <br/><br/><br/>
              </div>
            </div>  
            <div class="col-lg-3 col-xs-6 dontknowthename">
              <div class="cb-container">
                <div class="icon"><image src="img/hover/outbound.png" width="60px" height="60px"  ></div>
                  <br/><br/><br/>
                <h4 class="description" Align="center" style="color:#0c2e8a"><a href="" style="color:#0c2e8a"> Outbound calls</a></h4>
                <br/><br/><br/>
              </div>
            </div>  
            <div class="col-lg-3 col-xs-6 dontknowthename">
              <div class="cb-container">
                <div class="icon"><image src="img/hover/Content marketing, SEO, PPC, Banner Ads and Affiliate marketing Etc..png" width="60px" height="60px"  ></div>
                    <br/><br/><br/>
                <h4 class="description" Align="center" style="color:#0c2e8a"><a href="" style="color:#0c2e8a">Content marketing, SEO, PPC, Banner Ads and Affiliate marketing Etc.</a></h4>
                <br/><br/><br/>
              </div>
            </div> 
        </div>
                    <br/>
                   
            </div>


<div id="footer1"></div>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target=".header-top"><span class="icon fa fa-angle-up"></span></div>
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.fancybox.pack.js"></script>
<script src="js/jquery.fancybox-media.js"></script>
<script src="js/html5lightbox.js"></script>
<script src="js/isotope.js"></script> 


<!-- revolution slider js -->
<script src="assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="assets/revolution/js/extensions/revolution.extension.video.min.js"></script>

<script src="js/owl.carousel.min.js"></script>
<script src="js/validate.js"></script>
<script src="js/wow.js"></script>

<!-- gmap helper -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHzPSV2jshbjI8fqnC_C4L08ffnj5EN3A"></script>
<!--gmap script-->
<script src="js/gmaps.js"></script>
<script src="js/map-helper.js"></script>

<!-- bxslider -->
<script src="js/jquery.appear.js"></script>
<script src="js/jquery.countTo.js"></script>

<script src="js/script.js"></script>

</body>
</html>
